server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/farmconnect_auth?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  mail:
    host: smtp.gmail.com
    port: 587
    username: farmconnect4you@gmail.com
    password: lkfz nuip pejt pijk
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

security:
  jwt:
    secret: thisIsASecretKeyForJwtWhichIsAtLeast32BytesLong123
    access-expiration-ms: 900000
    refresh-expiration-ms: 1209600000
